/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/blog': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Listar posts publicados */
    get: {
      parameters: {
        query?: {
          locale?: string;
          page?: string;
          limit?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json':
              | {
                  _id?: string;
                  slug: string;
                  title: string;
                  description: string;
                  content?: string;
                  /** Format: date-time */
                  date: string;
                  published: boolean;
                  featured: boolean;
                  locale: string;
                  tags: string[];
                  image?: string | null;
                  author: string;
                  readingTime?: number | null;
                  /** Format: date-time */
                  createdAt?: string;
                  /** Format: date-time */
                  updatedAt?: string;
                }[]
              | {
                  data: {
                    _id?: string;
                    slug: string;
                    title: string;
                    description: string;
                    content?: string;
                    /** Format: date-time */
                    date: string;
                    published: boolean;
                    featured: boolean;
                    locale: string;
                    tags: string[];
                    image?: string | null;
                    author: string;
                    readingTime?: number | null;
                    /** Format: date-time */
                    createdAt?: string;
                    /** Format: date-time */
                    updatedAt?: string;
                  }[];
                  meta: {
                    page: number;
                    limit: number;
                    countTotal: number;
                    nextPage: boolean;
                    previousPage: boolean;
                  };
                };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/blog/{slug}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Obtener un post publicado por su slug */
    get: {
      parameters: {
        query?: {
          locale?: string;
        };
        header?: never;
        path: {
          slug: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              _id?: string;
              slug: string;
              title: string;
              description: string;
              content?: string;
              /** Format: date-time */
              date: string;
              published: boolean;
              featured: boolean;
              locale: string;
              tags: string[];
              image?: string | null;
              author: string;
              readingTime?: number | null;
              /** Format: date-time */
              createdAt?: string;
              /** Format: date-time */
              updatedAt?: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/blog': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Listar todos los posts, incluidos los borradores */
    get: {
      parameters: {
        query?: {
          locale?: string;
          page?: string;
          limit?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json':
              | {
                  _id?: string;
                  slug: string;
                  title: string;
                  description: string;
                  content?: string;
                  /** Format: date-time */
                  date: string;
                  published: boolean;
                  featured: boolean;
                  locale: string;
                  tags: string[];
                  image?: string | null;
                  author: string;
                  readingTime?: number | null;
                  /** Format: date-time */
                  createdAt?: string;
                  /** Format: date-time */
                  updatedAt?: string;
                }[]
              | {
                  data: {
                    _id?: string;
                    slug: string;
                    title: string;
                    description: string;
                    content?: string;
                    /** Format: date-time */
                    date: string;
                    published: boolean;
                    featured: boolean;
                    locale: string;
                    tags: string[];
                    image?: string | null;
                    author: string;
                    readingTime?: number | null;
                    /** Format: date-time */
                    createdAt?: string;
                    /** Format: date-time */
                    updatedAt?: string;
                  }[];
                  meta: {
                    page: number;
                    limit: number;
                    countTotal: number;
                    nextPage: boolean;
                    previousPage: boolean;
                  };
                };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    /** Crear un post */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            slug: string;
            title: string;
            description: string;
            content: string;
            date: unknown;
            published?: boolean;
            featured?: boolean;
            locale?: string;
            tags?: string[];
            /** Format: uri */
            image?: string;
            author?: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              _id?: string;
              slug: string;
              title: string;
              description: string;
              content?: string;
              /** Format: date-time */
              date: string;
              published: boolean;
              featured: boolean;
              locale: string;
              tags: string[];
              image?: string | null;
              author: string;
              readingTime?: number | null;
              /** Format: date-time */
              createdAt?: string;
              /** Format: date-time */
              updatedAt?: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/blog/{slug}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Obtener un post por su slug, incluidos los borradores */
    get: {
      parameters: {
        query?: {
          locale?: string;
        };
        header?: never;
        path: {
          slug: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              _id?: string;
              slug: string;
              title: string;
              description: string;
              content?: string;
              /** Format: date-time */
              date: string;
              published: boolean;
              featured: boolean;
              locale: string;
              tags: string[];
              image?: string | null;
              author: string;
              readingTime?: number | null;
              /** Format: date-time */
              createdAt?: string;
              /** Format: date-time */
              updatedAt?: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/blog/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Borrar un post */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    /** Actualizar un post */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            title?: string;
            description?: string;
            content?: string;
            date?: unknown;
            published?: boolean;
            featured?: boolean;
            tags?: string[];
            /** Format: uri */
            image?: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              _id?: string;
              slug: string;
              title: string;
              description: string;
              content?: string;
              /** Format: date-time */
              date: string;
              published: boolean;
              featured: boolean;
              locale: string;
              tags: string[];
              image?: string | null;
              author: string;
              readingTime?: number | null;
              /** Format: date-time */
              createdAt?: string;
              /** Format: date-time */
              updatedAt?: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    trace?: never;
  };
  '/api/v1/admin/blog/{id}/toggle-published': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Alternar el estado de publicación de un post */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              _id?: string;
              slug: string;
              title: string;
              description: string;
              content?: string;
              /** Format: date-time */
              date: string;
              published: boolean;
              featured: boolean;
              locale: string;
              tags: string[];
              image?: string | null;
              author: string;
              readingTime?: number | null;
              /** Format: date-time */
              createdAt?: string;
              /** Format: date-time */
              updatedAt?: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/projects': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Listar proyectos publicados */
    get: {
      parameters: {
        query?: {
          locale?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json':
              | {
                  _id?: string;
                  slug: string;
                  title: string;
                  description: string;
                  content?: string;
                  /** Format: date-time */
                  date: string;
                  published: boolean;
                  featured: boolean;
                  locale: string;
                  status: string;
                  tech: string[];
                  github?: string | null;
                  demo?: string | null;
                  image?: string | null;
                  order: number;
                  /** Format: date-time */
                  createdAt?: string;
                  /** Format: date-time */
                  updatedAt?: string;
                }[]
              | {
                  data: {
                    _id?: string;
                    slug: string;
                    title: string;
                    description: string;
                    content?: string;
                    /** Format: date-time */
                    date: string;
                    published: boolean;
                    featured: boolean;
                    locale: string;
                    status: string;
                    tech: string[];
                    github?: string | null;
                    demo?: string | null;
                    image?: string | null;
                    order: number;
                    /** Format: date-time */
                    createdAt?: string;
                    /** Format: date-time */
                    updatedAt?: string;
                  }[];
                  meta: {
                    page: number;
                    limit: number;
                    countTotal: number;
                    nextPage: boolean;
                    previousPage: boolean;
                  };
                };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/projects/featured': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Listar proyectos destacados */
    get: {
      parameters: {
        query?: {
          locale?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              _id?: string;
              slug: string;
              title: string;
              description: string;
              content?: string;
              /** Format: date-time */
              date: string;
              published: boolean;
              featured: boolean;
              locale: string;
              status: string;
              tech: string[];
              github?: string | null;
              demo?: string | null;
              image?: string | null;
              order: number;
              /** Format: date-time */
              createdAt?: string;
              /** Format: date-time */
              updatedAt?: string;
            }[];
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/projects/{slug}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Obtener proyecto publicado por slug */
    get: {
      parameters: {
        query?: {
          locale?: string;
        };
        header?: never;
        path: {
          slug: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              _id?: string;
              slug: string;
              title: string;
              description: string;
              content?: string;
              /** Format: date-time */
              date: string;
              published: boolean;
              featured: boolean;
              locale: string;
              status: string;
              tech: string[];
              github?: string | null;
              demo?: string | null;
              image?: string | null;
              order: number;
              /** Format: date-time */
              createdAt?: string;
              /** Format: date-time */
              updatedAt?: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/cms/site-settings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Obtener configuración del sitio */
    get: {
      parameters: {
        query?: {
          locale?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              _id?: string;
              locale: string;
              siteName: string;
              siteTitle: string;
              description: string;
              ogImage?: string | null;
              author: string;
              email: string;
              github?: string | null;
              linkedin?: string | null;
              manfred?: string | null;
              cvUrl?: string | null;
              /** Format: date-time */
              updatedAt?: string;
            } | null;
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/cms/hero': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Obtener contenido del hero */
    get: {
      parameters: {
        query?: {
          locale?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              _id?: string;
              locale: string;
              greeting: string;
              description: string;
              location: string;
              availability: string;
              profileImage: string;
              /** Format: date-time */
              updatedAt?: string;
            } | null;
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/cms/about': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Obtener contenido de About */
    get: {
      parameters: {
        query?: {
          locale?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              _id?: string;
              locale: string;
              badge: string;
              title: string;
              mainText: string;
              eduTitle: string;
              eduContent: string;
              philTitle: string;
              philContent: string;
              factsTitle: string;
              facts: string;
              image?: string | null;
              /** Format: date-time */
              updatedAt?: string;
            } | null;
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/cms/skills': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Listar skills */
    get: {
      parameters: {
        query?: {
          category?: string;
          published?: string | boolean;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              _id?: string;
              name: string;
              category: string;
              icon: string;
              order: number;
              published: boolean;
              /** Format: date-time */
              createdAt?: string;
              /** Format: date-time */
              updatedAt?: string;
            }[];
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/cms/experiences': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Listar experiencias */
    get: {
      parameters: {
        query?: {
          locale?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              _id?: string;
              locale: string;
              company: string;
              position: string;
              period: string;
              tasks: string[];
              color: string;
              order: number;
              published: boolean;
              /** Format: date-time */
              createdAt?: string;
              /** Format: date-time */
              updatedAt?: string;
            }[];
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/cms/testimonials': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Listar testimonios */
    get: {
      parameters: {
        query?: {
          locale?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              _id?: string;
              locale: string;
              author: string;
              initials: string;
              position: string;
              text: string;
              date: string;
              gradient: string;
              order: number;
              published: boolean;
              /** Format: date-time */
              createdAt?: string;
              /** Format: date-time */
              updatedAt?: string;
            }[];
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/storage/download-url': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Obtener URL prefirmada de descarga */
    get: {
      parameters: {
        query: {
          key: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              url: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/storage/upload-url': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Obtener URL prefirmada de subida */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            key: string;
            /** @enum {string} */
            contentType: 'image/png' | 'image/jpeg' | 'image/webp' | 'image/avif';
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              uploadUrl: string;
              key: string;
              expiresIn: number;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/storage/objects': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Listar objetos del bucket */
    get: {
      parameters: {
        query?: {
          prefix?: string;
          continuationToken?: string;
          maxKeys?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              objects: {
                key: string;
                size: number;
                /** Format: date-time */
                lastModified: string;
              }[];
              folders: string[];
              nextToken?: string;
              prefix: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    /** Borrar un objeto */
    delete: {
      parameters: {
        query: {
          key: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/storage/objects/count': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Contar objetos bajo un prefijo */
    get: {
      parameters: {
        query?: {
          prefix?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              prefix: string;
              totalObjects: number;
              totalBytes: number;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/storage/objects/copy': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Copiar un objeto */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            sourceKey: string;
            destKey: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/storage/objects/bulk-delete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Borrado masivo de objetos */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            keys: string[];
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              deleted: number;
              failed: number;
              total: number;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/storage/notify-upload': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Notificar subida completada */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            key: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/storage/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Estado del almacenamiento */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              s3: boolean;
              database: boolean;
              timestamp: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/dashboard/recent-activity': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Actividad reciente: 5 posts + 5 proyectos, top 10 por última modificación */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {string} */
              type: 'post' | 'project';
              _id?: string;
              slug: string;
              title: string;
              locale: string;
              /** Format: date-time */
              date?: string;
              published: boolean;
            }[];
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Identidad verificada de la petición actual */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {string} */
              tokenType: 'session_token' | 'api_key' | 'm2m_token';
              userId: string | null;
              email: string | null;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/dev-token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Emite un token de sesión del administrador (solo desarrollo) para Postman/Swagger */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              token: string;
              expiresInSeconds: number;
              userId: string;
              email: string | null;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        502: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Listar usuarios */
    get: {
      parameters: {
        query?: {
          limit?: number;
          offset?: number;
          query?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data: {
                id: string;
                email: string | null;
                firstName: string | null;
                lastName: string | null;
                username: string | null;
                imageUrl: string;
                banned: boolean;
                locked: boolean;
                publicMetadata: {
                  [key: string]: unknown;
                };
                createdAt: number;
                lastSignInAt: number | null;
              }[];
              totalCount: number;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    /** Alta administrativa de usuario */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** Format: email */
            emailAddress: string;
            password?: string;
            firstName?: string;
            lastName?: string;
            username?: string;
            publicMetadata?: {
              [key: string]: unknown;
            };
          };
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              id: string;
              email: string | null;
              firstName: string | null;
              lastName: string | null;
              username: string | null;
              imageUrl: string;
              banned: boolean;
              locked: boolean;
              publicMetadata: {
                [key: string]: unknown;
              };
              createdAt: number;
              lastSignInAt: number | null;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/users/count': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Contar usuarios */
    get: {
      parameters: {
        query?: {
          limit?: number;
          offset?: number;
          query?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              totalCount: number;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/users/invitations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Listar invitaciones */
    get: {
      parameters: {
        query?: {
          limit?: number;
          offset?: number;
          status?: 'pending' | 'accepted' | 'revoked' | 'expired';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data: {
                id: string;
                email: string;
                status: string;
                url: string | null;
                createdAt: number;
                updatedAt: number;
              }[];
              totalCount: number;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    /** Invitar a un usuario */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** Format: email */
            emailAddress: string;
            /** Format: uri */
            redirectUrl?: string;
            publicMetadata?: {
              [key: string]: unknown;
            };
            expiresInDays?: number;
          };
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              id: string;
              email: string;
              status: string;
              url: string | null;
              createdAt: number;
              updatedAt: number;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/users/invitations/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revocar invitación */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              id: string;
              email: string;
              status: string;
              url: string | null;
              createdAt: number;
              updatedAt: number;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/users/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Obtener usuario por id */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              id: string;
              email: string | null;
              firstName: string | null;
              lastName: string | null;
              username: string | null;
              imageUrl: string;
              banned: boolean;
              locked: boolean;
              publicMetadata: {
                [key: string]: unknown;
              };
              createdAt: number;
              lastSignInAt: number | null;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    /** Borrar usuario */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    /** Actualizar usuario */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            firstName?: string;
            lastName?: string;
            username?: string;
            publicMetadata?: {
              [key: string]: unknown;
            };
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              id: string;
              email: string | null;
              firstName: string | null;
              lastName: string | null;
              username: string | null;
              imageUrl: string;
              banned: boolean;
              locked: boolean;
              publicMetadata: {
                [key: string]: unknown;
              };
              createdAt: number;
              lastSignInAt: number | null;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
